defmodule Muse.Tools.GetLogs do
  @moduledoc """
  Read-only tool: retrieve application logs from the circular buffer with filtering.

  Reads from `Muse.LogBuffer.list()` which returns newest-first entries.
  Supports `tail`, `grep`, and `level` filters. Logs generated by Muse's own
  tool calls are excluded via metadata filtering.

  ## Output format

      %{
        entries: [
          %{
            id: 123,
            timestamp: "2024-01-15T10:30:00Z",
            level: "info",
            source: "app",
            message: "Server started",
            metadata: %{}
          }
        ],
        count: 15,
        filters_applied: %{tail: 50, grep: nil, level: nil}
      }

  ## Edge cases

    * No log entries → `%{entries: [], count: 0}`
    * `tail=0` → return all (capped at 200)
    * Large log volume → capped at 200 entries
    * Logs from tool calls → excluded by metadata tag
    * Log buffer not initialized → clear error
    * Invalid level → clear error
  """

  alias Muse.Tool.Result
  alias Muse.LogEntry

  @max_entries 200
  @valid_levels ~w(emergency alert critical error warning notice info debug)a

  @doc """
  Execute the get_logs tool.

  ## Arguments

    * `"tail"` — number of recent entries to return (0 returns all, capped at 200, required)
    * `"grep"` — optional regex pattern to filter messages
    * `"level"` — optional log level filter (emergency|alert|critical|error|warning|notice|info|debug)

  """
  @spec execute(map(), map()) :: Result.t()
  def execute(args, _context) do
    with {:ok, tail} <- require_tail(args),
         :ok <- validate_tail(tail),
         {:ok, level} <- validate_level(Map.get(args, "level")),
         {:ok, grep} <- validate_grep(Map.get(args, "grep")),
         {:ok, entries} <- fetch_log_entries() do
      filtered =
        entries
        |> exclude_tool_calls()
        |> filter_by_level(level)
        |> filter_by_grep(grep)
        |> apply_tail(tail)

      Result.ok("get_logs", %{
        entries: Enum.map(filtered, &entry_to_map/1),
        count: length(filtered),
        filters_applied: %{tail: tail, grep: grep, level: level}
      })
    else
      {:error, reason} ->
        Result.error("get_logs", reason)
    end
  end

  # -- Validation ---------------------------------------------------------------

  defp require_tail(args) do
    case Map.get(args, "tail") do
      nil -> {:error, "tail is required"}
      tail when is_integer(tail) -> {:ok, tail}
      _ -> {:error, "tail must be an integer"}
    end
  end

  defp validate_tail(tail) when tail >= 0, do: :ok
  defp validate_tail(_tail), do: {:error, "tail must be a non-negative integer"}

  defp validate_level(nil), do: {:ok, nil}

  defp validate_level(level) when is_binary(level) do
    atom_level = String.to_existing_atom(level)

    if atom_level in @valid_levels do
      {:ok, atom_level}
    else
      {:error, "invalid level: #{level}"}
    end
  rescue
    ArgumentError ->
      {:error, "invalid level: #{level}"}
  end

  defp validate_level(_), do: {:error, "level must be a string"}

  defp validate_grep(nil), do: {:ok, nil}

  defp validate_grep(pattern) when is_binary(pattern) do
    case Regex.compile(pattern) do
      {:ok, _regex} -> {:ok, pattern}
      {:error, {reason, _pos}} -> {:error, "invalid grep pattern: #{reason}"}
    end
  end

  defp validate_grep(_), do: {:error, "grep must be a string"}

  # -- Log buffer access --------------------------------------------------------

  defp fetch_log_entries do
    case Process.whereis(Muse.LogBuffer) do
      nil ->
        {:error, "log buffer is not initialized"}

      pid ->
        if Process.alive?(pid) do
          {:ok, Muse.LogBuffer.list()}
        else
          {:error, "log buffer is not initialized"}
        end
    end
  rescue
    _ -> {:error, "log buffer is not available"}
  catch
    :exit, _ -> {:error, "log buffer is not available"}
  end

  # -- Filtering ----------------------------------------------------------------

  defp exclude_tool_calls(entries) do
    Enum.reject(entries, fn %LogEntry{metadata: meta} ->
      Map.get(meta, :muse_tool_call, false) == true
    end)
  end

  defp filter_by_level(entries, nil), do: entries

  defp filter_by_level(entries, level) do
    Enum.filter(entries, &(&1.level == level))
  end

  defp filter_by_grep(entries, nil), do: entries

  defp filter_by_grep(entries, pattern) do
    {:ok, regex} = Regex.compile(pattern)
    Enum.filter(entries, &Regex.match?(regex, &1.message))
  end

  defp apply_tail(entries, 0) do
    Enum.take(entries, @max_entries)
  end

  defp apply_tail(entries, tail) do
    entries
    |> Enum.take(min(tail, @max_entries))
  end

  # -- Formatting --------------------------------------------------------------

  defp entry_to_map(%LogEntry{} = entry) do
    %{
      id: entry.id,
      timestamp: DateTime.to_iso8601(entry.timestamp),
      level: Atom.to_string(entry.level),
      source: Atom.to_string(entry.source),
      message: entry.message,
      metadata: entry.metadata
    }
  end
end
