defmodule Muse.CLI.ReleaseCommand do
  @moduledoc """
  Custom Mix release command for Muse.

  When Muse is built as a Mix release (`MIX_ENV=prod mix release`),
  the generated `bin/muse` script delegates here via:

      bin/muse eval "Muse.CLI.ReleaseCommand.main(ARGV)"

  This module provides the same interface as `mix muse` and `./muse`
  (escript): it stashes argv, sets `:source_mode?` to `false`, and
  starts the `:muse` application.

  ## Usage (from a release)

      bin/muse --tui --no-web
      bin/muse --repl
      bin/muse --help
      bin/muse --no-web --workspace /path

  ## Why not a custom VM args file?

  The `bin/muse` script generated by Mix releases supports `eval`,
  `rpc`, and `start` but does not natively pass argv to the
  application.  The recommended pattern is `bin/muse eval
  "Muse.CLI.ReleaseCommand.main(ARGV)"` or a small shell wrapper.

  The `bin/muse` release script itself can be wrapped — see
  `rel/overlays/bin/muse_cli` for a convenience script that
  forwards all arguments.
  """


  @doc """
  Release entrypoint. Behaves like `Muse.CLI.Main.main/1` but
  intended for `bin/muse eval` invocation.
  """
  @spec main([String.t()]) :: no_return()
  def main(args) do
    Application.put_env(:muse, :boot_args, args)
    Application.put_env(:muse, :source_mode?, false)

    result = Application.ensure_all_started(:muse)
    Process.sleep(:infinity)
    # Unreachable — keeps type spec honest
    result
  end

  @doc """
  Help entrypoint for the release. Prints usage and exits.

  Useful when the caller wants to check flags without starting the app:

      bin/muse eval "Muse.CLI.ReleaseCommand.print_help()"
  """
  @spec print_help() :: no_return()
  def print_help do
    IO.puts(Muse.Application.help_text())
    System.halt(0)
  end
end
